// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spotlys.Infrastructure;

#nullable disable

namespace Spotlys.Infrastructure.Migrations
{
    [DbContext(typeof(SpotlysDbContext))]
    [Migration("20260916082438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spotlys.Domain.Pricing.PriceObservation", b =>
                {
                    b.Property<string>("Zone")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.Property<DateTimeOffset>("HourStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_start_utc");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal?>("CurrencyRate")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("currency_rate");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("PriceExVatOrePerKwh")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("price_ex_vat");

                    b.HasKey("Zone", "HourStartUtc", "Source");

                    b.HasIndex("HourStartUtc");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HourStartUtc"), "brin");

                    b.ToTable("price_observation", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Ingestion.IngestionRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<int?>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WindowFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_from");

                    b.Property<DateTimeOffset?>("WindowTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_to");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt");

                    b.ToTable("ingestion_run", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
