// <auto-generated />
// EF Core migration, scaffolded by `dotnet ef migrations add`, then hand-edited for the
// partitioning DDL (docs/adr/0001-postgres-partitioning.md) -- not held to the same
// analyzer strictness as hand-authored code, same as every other EF migration.
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Spotlys.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ingestion_run",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn),
                    job_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    started_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    finished_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    rows = table.Column<int>(type: "integer", nullable: true),
                    window_from = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    window_to = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    error = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ingestion_run", x => x.id);
                });

            // price_observation is created partitioned by month (docs/ARCHITECTURE.md §4:
            // "native declarative partitioning by month on the large tables"), which EF
            // Core's fluent model can't express -- hence raw SQL instead of CreateTable.
            // See docs/adr/0001-postgres-partitioning.md.
            //
            // The partition key (hour_start_utc) must be part of every unique constraint,
            // which it already is via the natural key (zone, hour_start_utc, source).
            //
            // Partitions are pre-created for a wide covering range: hvakosterstrommen's own
            // archive starts 2022-09-01 (docs/DATA.md §1), through a few months past this
            // migration's authoring date. Creating future months' partitions is a manual or
            // follow-up-job concern -- no such job exists yet in docs/ARCHITECTURE.md §5's
            // job table, called out honestly in the ADR rather than silently assumed.
            migrationBuilder.Sql(
                """
                CREATE TABLE price_observation (
                    zone            character varying(3)  NOT NULL,
                    hour_start_utc  timestamptz            NOT NULL,
                    source          character varying(20)  NOT NULL,
                    price_ex_vat    numeric(10,4)           NOT NULL,
                    currency_rate   numeric(10,6),
                    observed_at_utc timestamptz             NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_price_observation" PRIMARY KEY (zone, hour_start_utc, source)
                ) PARTITION BY RANGE (hour_start_utc);
                """);

            migrationBuilder.Sql(BuildMonthlyPartitionSql());

            migrationBuilder.CreateIndex(
                name: "IX_ingestion_run_job_name_started_at",
                table: "ingestion_run",
                columns: new[] { "job_name", "started_at" });

            // Creating an index on a partitioned parent in Postgres 11+ automatically
            // creates a matching index on every existing (and future) partition.
            migrationBuilder.CreateIndex(
                name: "IX_price_observation_hour_start_utc",
                table: "price_observation",
                column: "hour_start_utc")
                .Annotation("Npgsql:IndexMethod", "brin");
        }

        /// <summary>Builds CREATE TABLE ... PARTITION OF statements for every month from
        /// 2022-09 (hvakosterstrommen's archive start) through 2027-03.</summary>
        private static string BuildMonthlyPartitionSql()
        {
            var start = new DateOnly(2022, 9, 1);
            var end = new DateOnly(2027, 4, 1); // exclusive upper bound of the last partition
            var sql = new System.Text.StringBuilder();

            for (var month = start; month < end; month = month.AddMonths(1))
            {
                var next = month.AddMonths(1);
                var partitionName = $"price_observation_y{month.Year}m{month.Month:D2}";
                sql.AppendLine(
                    $"""
                    CREATE TABLE {partitionName} PARTITION OF price_observation
                        FOR VALUES FROM ('{month:yyyy-MM-dd}') TO ('{next:yyyy-MM-dd}');
                    """);
            }

            return sql.ToString();
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ingestion_run");

            migrationBuilder.DropTable(
                name: "price_observation");
        }
    }
}
