// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spotlys.Infrastructure;

#nullable disable

namespace Spotlys.Infrastructure.Migrations
{
    [DbContext(typeof(SpotlysDbContext))]
    [Migration("20260922210037_AddIdentityAndMeterProfile")]
    partial class AddIdentityAndMeterProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("app_user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("app_user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("app_user_token", (string)null);
                });

            modelBuilder.Entity("Spotlys.Domain.Pricing.PriceObservation", b =>
                {
                    b.Property<string>("Zone")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.Property<DateTimeOffset>("HourStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_start_utc");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal?>("CurrencyRate")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("currency_rate");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("PriceExVatOrePerKwh")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("price_ex_vat");

                    b.HasKey("Zone", "HourStartUtc", "Source");

                    b.HasIndex("HourStartUtc");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HourStartUtc"), "brin");

                    b.ToTable("price_observation", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Accounts.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Accounts.MeterProfileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsumptionRetentionYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("consumption_retention_years");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("GridCompanyId")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grid_company_id");

                    b.Property<bool>("IsCabin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cabin");

                    b.Property<decimal>("SupplierMarkupExVatOrePerKwh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("supplier_markup_ore");

                    b.Property<decimal>("SupplierMonthlyFeeExVatNok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("supplier_monthly_fee_nok");

                    b.Property<string>("SupportScheme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("support_scheme");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("GridCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("meter_profile", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Forecasting.ModelVersionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BacktestMae")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("backtest_mae");

                    b.Property<decimal?>("BacktestSkill")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("backtest_skill");

                    b.Property<string>("GitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("git_sha");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("OnnxPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("onnx_path");

                    b.Property<string>("OnnxSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("onnx_sha256");

                    b.Property<decimal>("Quantile")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("quantile");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("regime");

                    b.Property<DateTimeOffset>("TrainDataToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("train_data_to");

                    b.Property<DateTimeOffset>("TrainedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trained_at_utc");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("Zone", "Regime", "Quantile")
                        .IsUnique()
                        .HasFilter("is_active");

                    b.HasIndex("Zone", "Regime", "Quantile", "TrainedAtUtc");

                    b.ToTable("model_version", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Hydrology.HydrologyObservationRow", b =>
                {
                    b.Property<string>("Zone")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<float>("CapacityTwh")
                        .HasColumnType("real")
                        .HasColumnName("capacity_twh");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<float>("FillFraction")
                        .HasColumnType("real")
                        .HasColumnName("fill_fraction");

                    b.Property<float>("FillTwh")
                        .HasColumnType("real")
                        .HasColumnName("fill_twh");

                    b.Property<DateTimeOffset?>("NextPublicationUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_publication_utc");

                    b.HasKey("Zone", "WeekStartDate", "Source");

                    b.ToTable("hydrology_observation", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Hydrology.HydrologyWeekNormRow", b =>
                {
                    b.Property<string>("Zone")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.Property<int>("IsoWeek")
                        .HasColumnType("integer")
                        .HasColumnName("iso_week");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<float>("MaxFillFraction")
                        .HasColumnType("real")
                        .HasColumnName("max_fill_fraction");

                    b.Property<float>("MedianFillFraction")
                        .HasColumnType("real")
                        .HasColumnName("median_fill_fraction");

                    b.Property<float>("MinFillFraction")
                        .HasColumnType("real")
                        .HasColumnName("min_fill_fraction");

                    b.HasKey("Zone", "IsoWeek");

                    b.ToTable("hydrology_week_norm", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Ingestion.IngestionRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<int?>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WindowFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_from");

                    b.Property<DateTimeOffset?>("WindowTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_to");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt");

                    b.ToTable("ingestion_run", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Metering.ConsumptionReadingRow", b =>
                {
                    b.Property<Guid>("MeterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_profile_id");

                    b.Property<DateTimeOffset>("HourStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_start_utc");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<decimal>("Kwh")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("kwh");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.HasKey("MeterProfileId", "HourStartUtc");

                    b.HasIndex("HourStartUtc");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HourStartUtc"), "brin");

                    b.ToTable("consumption_reading", "metering");
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Metering.ConsumptionRetentionPurgeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("MeterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_profile_id");

                    b.Property<DateTimeOffset>("PurgedThroughUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_through_utc");

                    b.Property<int>("RowsDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_deleted");

                    b.Property<DateTimeOffset>("RunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at_utc");

                    b.HasKey("Id");

                    b.ToTable("consumption_retention_purge", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Pricing.GridCompanyRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("grid_company", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Pricing.GridTariffRow", b =>
                {
                    b.Property<string>("GridCompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grid_company_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<string>("CapacitySteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capacity_steps");

                    b.Property<decimal>("EnergyDayOre")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("energy_day_ore");

                    b.Property<decimal>("EnergyNightOre")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("energy_night_ore");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("GridCompanyId", "ValidFrom");

                    b.ToTable("grid_tariff", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Pricing.SchemeParameterRow", b =>
                {
                    b.Property<string>("Scheme")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scheme");

                    b.Property<string>("Parameter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value");

                    b.HasKey("Scheme", "Parameter", "ValidFrom");

                    b.ToTable("scheme_parameter", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Weather.WeatherFetchCacheRow", b =>
                {
                    b.Property<string>("PointId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("point_id");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.HasKey("PointId");

                    b.ToTable("weather_fetch_cache", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Weather.WeatherForecastRow", b =>
                {
                    b.Property<string>("PointId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("point_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset>("ValidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_at_utc");

                    b.Property<float?>("CloudFrac")
                        .HasColumnType("real")
                        .HasColumnName("cloud_frac");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<float?>("PrecipMm")
                        .HasColumnType("real")
                        .HasColumnName("precip_mm");

                    b.Property<float?>("TempC")
                        .HasColumnType("real")
                        .HasColumnName("temp_c");

                    b.Property<float?>("WindDirDeg")
                        .HasColumnType("real")
                        .HasColumnName("wind_dir_deg");

                    b.Property<float?>("WindMs")
                        .HasColumnType("real")
                        .HasColumnName("wind_ms");

                    b.HasKey("PointId", "IssuedAtUtc", "ValidAtUtc");

                    b.HasIndex("ValidAtUtc");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValidAtUtc"), "brin");

                    b.ToTable("weather_forecast", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Weather.WeatherPointRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("AltitudeM")
                        .HasColumnType("integer")
                        .HasColumnName("altitude_m");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lon")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.ToTable("weather_point", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Accounts.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Accounts.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Accounts.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Accounts.MeterProfileRow", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Pricing.GridCompanyRow", null)
                        .WithMany()
                        .HasForeignKey("GridCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spotlys.Infrastructure.Accounts.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Metering.ConsumptionReadingRow", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Accounts.MeterProfileRow", null)
                        .WithMany()
                        .HasForeignKey("MeterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Weather.WeatherFetchCacheRow", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Weather.WeatherPointRow", null)
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Weather.WeatherForecastRow", b =>
                {
                    b.HasOne("Spotlys.Infrastructure.Weather.WeatherPointRow", null)
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
