// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spotlys.Infrastructure;

#nullable disable

namespace Spotlys.Infrastructure.Migrations
{
    [DbContext(typeof(SpotlysDbContext))]
    [Migration("20260917101533_SeedPricingData")]
    partial class SeedPricingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spotlys.Domain.Pricing.PriceObservation", b =>
                {
                    b.Property<string>("Zone")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("zone");

                    b.Property<DateTimeOffset>("HourStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_start_utc");

                    b.Property<string>("Source")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal?>("CurrencyRate")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("currency_rate");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("PriceExVatOrePerKwh")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("price_ex_vat");

                    b.HasKey("Zone", "HourStartUtc", "Source");

                    b.HasIndex("HourStartUtc");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HourStartUtc"), "brin");

                    b.ToTable("price_observation", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Ingestion.IngestionRunRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<int?>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WindowFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_from");

                    b.Property<DateTimeOffset?>("WindowTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_to");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt");

                    b.ToTable("ingestion_run", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Pricing.GridCompanyRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("grid_company", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Pricing.GridTariffRow", b =>
                {
                    b.Property<string>("GridCompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grid_company_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<string>("CapacitySteps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capacity_steps");

                    b.Property<decimal>("EnergyDayOre")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("energy_day_ore");

                    b.Property<decimal>("EnergyNightOre")
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("energy_night_ore");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("GridCompanyId", "ValidFrom");

                    b.ToTable("grid_tariff", (string)null);
                });

            modelBuilder.Entity("Spotlys.Infrastructure.Pricing.SchemeParameterRow", b =>
                {
                    b.Property<string>("Scheme")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scheme");

                    b.Property<string>("Parameter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value");

                    b.HasKey("Scheme", "Parameter", "ValidFrom");

                    b.ToTable("scheme_parameter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
