// <auto-generated />
// The three NO2 sample points (docs/DATA.md §2's own example: a population-weighted
// demand point, a coastal/wind point, a hydrological catchment point), coordinates rounded
// to four decimals / nearest metre per docs/DATA.md §2. Kristiansand is the exact point
// already proven live in spike/fetch_weather.py; Lista and Byglandsfjord are this
// session's own reasonable choice of real Agder locations for the other two roles --
// docs/DATA.md doesn't name canonical points, so there is no single "correct" answer here,
// only a defensible one.
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Spotlys.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedWeatherPoints : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                INSERT INTO weather_point (id, zone, kind, name, lat, lon, altitude_m) VALUES
                    ('no2-kristiansand', 'NO2', 'demand', 'Kristiansand', 58.1467, 7.9956, 15),
                    ('no2-lista', 'NO2', 'coastal', 'Lista (Farsund)', 58.1053, 6.6165, 5),
                    ('no2-byglandsfjord', 'NO2', 'catchment', 'Byglandsfjord (Setesdal)', 58.6667, 7.8167, 200);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM weather_point WHERE id IN ('no2-kristiansand', 'no2-lista', 'no2-byglandsfjord');
                """);
        }
    }
}
