// <auto-generated />
// EF Core migration, scaffolded then hand-filled with real, sourced seed data -- every
// row's value and source_url were fetched live from the cited page during Phase 2
// planning/implementation (docs/DOMAIN.md §7: "Hard-coding 77 or 50 anywhere in
// application code is a review-blocking defect" -- this table is where they're allowed
// to live, with provenance). Raw SQL rather than EF's HasData() seeding to avoid baking
// large JSON blobs into the model snapshot every future migration compares against.
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Spotlys.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedPricingData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                INSERT INTO grid_company (id, name) VALUES
                    ('glitre-nett', 'Glitre Nett (Agder/Kristiansand)'),
                    ('l-nett', 'L-nett (Sør-Rogaland/Stavanger)'),
                    ('elvia', 'Elvia (Oslo/Viken)');
                """);

            // Scheme parameters. Every row's source_url was fetched live during Phase 2
            // planning -- see docs/DOMAIN.md §3 for the domain rules these implement.
            migrationBuilder.Sql(
                """
                INSERT INTO scheme_parameter (scheme, parameter, valid_from, valid_to, value, source_url) VALUES
                    ('stromstotte', 'threshold_ex_vat_ore', '2026-01-01', NULL, 77.00,
                        'https://www.nve.no/reguleringsmyndigheten/kunde/stroem/dette-er-stroemstoetteordningen/'),
                    ('stromstotte', 'support_rate', '2023-09-01', NULL, 0.90,
                        'https://www.nve.no/reguleringsmyndigheten/kunde/stroem/dette-er-stroemstoetteordningen/'),
                    ('norgespris', 'rate_ex_vat_ore', '2026-01-01', NULL, 40.00,
                        'https://www.regjeringen.no/no/tema/energi/strom/sporsmal-og-svar-om-norgespris/id3089310/'),
                    ('norgespris', 'cap_kwh_month_home', '2025-10-01', NULL, 5000,
                        'https://www.regjeringen.no/no/tema/energi/strom/sporsmal-og-svar-om-norgespris/id3089310/'),
                    ('norgespris', 'cap_kwh_month_cabin', '2025-10-01', NULL, 1000,
                        'https://www.regjeringen.no/no/tema/energi/strom/sporsmal-og-svar-om-norgespris/id3089310/'),
                    ('vat', 'standard_rate', '2026-01-01', NULL, 0.25,
                        'https://lovdata.no/dokument/STV/forskrift/2025-12-18-2752'),
                    ('vat', 'no4_rate', '2018-01-01', NULL, 0.00,
                        'https://lovdata.no/dokument/STV/forskrift/2025-12-18-2752'),
                    ('forbruksavgift', 'rate_ex_vat_ore_per_kwh', '2026-01-01', NULL, 7.13,
                        'https://lovdata.no/dokument/STV/forskrift/2025-12-18-2760/%C2%A72'),
                    ('enova', 'rate_ex_vat_ore_per_kwh', '2026-01-01', NULL, 1.00,
                        'https://www.glitrenett.no/kunde/nettleie-og-priser/nettleiepriser-privatkunde');
                """);

            // Grid tariffs. Day/night rates and capacity steps are the grid companies' own
            // published figures (incl. VAT / 1.25 = ex VAT, matching docs/DOMAIN.md's
            // storage convention), fetched live from each source_url.
            migrationBuilder.Sql(
                """
                INSERT INTO grid_tariff (grid_company_id, valid_from, energy_day_ore, energy_night_ore, capacity_steps, source_url) VALUES
                (
                    'glitre-nett', '2026-07-01', 33.7280, 21.7280,
                    '[
                        {"FromKw":0,"ToKw":2,"MonthlyExVatNok":128.00},
                        {"FromKw":2,"ToKw":5,"MonthlyExVatNok":186.00},
                        {"FromKw":5,"ToKw":10,"MonthlyExVatNok":312.00},
                        {"FromKw":10,"ToKw":15,"MonthlyExVatNok":584.00},
                        {"FromKw":15,"ToKw":20,"MonthlyExVatNok":772.00},
                        {"FromKw":20,"ToKw":25,"MonthlyExVatNok":968.00},
                        {"FromKw":25,"ToKw":50,"MonthlyExVatNok":1508.00},
                        {"FromKw":50,"ToKw":75,"MonthlyExVatNok":2392.00},
                        {"FromKw":75,"ToKw":100,"MonthlyExVatNok":3192.00},
                        {"FromKw":100,"ToKw":999999,"MonthlyExVatNok":5332.00}
                    ]'::jsonb,
                    'https://www.glitrenett.no/kunde/nettleie-og-priser/nettleiepriser-privatkunde'
                ),
                (
                    'l-nett', '2026-01-01', 25.6000, 13.6000,
                    '[
                        {"FromKw":0,"ToKw":2,"MonthlyExVatNok":120.00},
                        {"FromKw":2,"ToKw":5,"MonthlyExVatNok":200.00},
                        {"FromKw":5,"ToKw":10,"MonthlyExVatNok":320.00},
                        {"FromKw":10,"ToKw":15,"MonthlyExVatNok":520.00},
                        {"FromKw":15,"ToKw":20,"MonthlyExVatNok":720.00},
                        {"FromKw":20,"ToKw":999999,"MonthlyExVatNok":920.00}
                    ]'::jsonb,
                    'https://www.l-nett.no/nettleie/priser-og-vilkar-privat/'
                ),
                (
                    'elvia', '2026-07-01', 37.1200, 25.1200,
                    '[
                        {"FromKw":0,"ToKw":2,"MonthlyExVatNok":120.00},
                        {"FromKw":2,"ToKw":5,"MonthlyExVatNok":200.00},
                        {"FromKw":5,"ToKw":10,"MonthlyExVatNok":336.00},
                        {"FromKw":10,"ToKw":15,"MonthlyExVatNok":468.00},
                        {"FromKw":15,"ToKw":999999,"MonthlyExVatNok":604.00}
                    ]'::jsonb,
                    'https://www.elvia.no/nettleie/alt-om-nettleiepriser/nettleie-pris/'
                );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM grid_tariff WHERE grid_company_id IN ('glitre-nett', 'l-nett', 'elvia');
                DELETE FROM scheme_parameter WHERE scheme IN ('stromstotte', 'norgespris', 'vat', 'forbruksavgift', 'enova');
                DELETE FROM grid_company WHERE id IN ('glitre-nett', 'l-nett', 'elvia');
                """);
        }
    }
}
